"""Offline supervised trainer for CubeValueNet.

Training data: (encoded_state, scramble_depth_label) pairs generated by scrambling
solved puzzles to known depths. Loss is MSE between predicted value and actual depth.
"""
from __future__ import annotations

import logging
import math
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

import mlx.core as mx
import mlx.nn as nn
import mlx.optimizers as optim

from rubiks_solve.solvers.cnn.model import CubeValueNet

logger = logging.getLogger(__name__)


@dataclass
class CNNTrainerConfig:
    """Hyperparameters and paths for CNN value-network training.

    Attributes:
        learning_rate:   Adam learning rate.
        batch_size:      Number of samples per gradient step.
        epochs:          Total training epochs.
        checkpoint_dir:  Directory in which to save ``*.npz`` checkpoints.
        log_interval:    Log metrics every this many epochs.
    """

    learning_rate: float = 1e-4
    batch_size: int = 512
    epochs: int = 100
    checkpoint_dir: Path = Path("models/cnn")
    log_interval: int = 10


class CNNTrainer:
    """Trains :class:`CubeValueNet` via supervised regression on scramble depth.

    Args:
        model:  The value network to train (in-place weight updates).
        config: Training hyperparameters.
    """

    def __init__(self, model: CubeValueNet, config: CNNTrainerConfig) -> None:
        self.model = model
        self.config = config
        self.optimizer = optim.Adam(learning_rate=config.learning_rate)
        self._logger = logging.getLogger(self.__class__.__qualname__)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _mse_and_mae(model: CubeValueNet, x: mx.array, y: mx.array) -> tuple[mx.array, mx.array]:
        """Compute MSE loss and MAE for a batch.

        Args:
            model: Value network.
            x:     Encoded states, shape ``(batch, input_size)``.
            y:     Depth labels, shape ``(batch,)`` or ``(batch, 1)``.

        Returns:
            Tuple of (mse_loss, mae) as scalar ``mx.array`` values.
        """
        preds = model(x)  # (batch, 1)
        preds = preds.squeeze(-1)  # (batch,)
        y_flat = y.reshape(-1)

        mse = nn.losses.mse_loss(preds, y_flat, reduction="mean")
        mae = mx.mean(mx.abs(preds - y_flat))
        return mse, mae

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def train_epoch(
        self,
        states: np.ndarray,
        labels: np.ndarray,
    ) -> dict[str, float]:
        """Train the model for one full epoch over the provided dataset.

        The dataset is shuffled at the start of each epoch and then processed
        in mini-batches of size ``config.batch_size``.

        Args:
            states: Float32 array of shape ``(N, input_size)`` containing
                    encoder outputs.
            labels: Float32 array of shape ``(N,)`` containing scramble depths
                    (regression targets).

        Returns:
            Dict with keys ``'loss'`` (mean MSE) and ``'mae'`` (mean absolute error).
        """
        n = len(states)
        indices = np.random.permutation(n)
        states = states[indices]
        labels = labels[indices].astype(np.float32)

        n_batches = math.ceil(n / self.config.batch_size)
        total_loss = 0.0
        total_mae = 0.0

        # Build a closure that receives the model's trainable parameters via
        # MLX's functional API. nn.value_and_grad wraps the loss function so
        # that gradients flow through `model`.
        def loss_fn(model: CubeValueNet, x: mx.array, y: mx.array) -> mx.array:
            mse, _ = CNNTrainer._mse_and_mae(model, x, y)
            return mse

        loss_and_grad_fn = nn.value_and_grad(self.model, loss_fn)

        for i in range(n_batches):
            start = i * self.config.batch_size
            end = min(start + self.config.batch_size, n)

            x_batch = mx.array(states[start:end])
            y_batch = mx.array(labels[start:end])

            loss_val, grads = loss_and_grad_fn(self.model, x_batch, y_batch)

            self.optimizer.update(self.model, grads)

            # Compute MAE for logging (reuse forward pass result).
            _, mae_val = CNNTrainer._mse_and_mae(self.model, x_batch, y_batch)

            # Force evaluation of the lazy computation graph.
            mx.eval(loss_val, mae_val, self.model.parameters())

            total_loss += float(loss_val)
            total_mae += float(mae_val)

        return {
            "loss": total_loss / n_batches,
            "mae": total_mae / n_batches,
        }

    def train(
        self,
        states: np.ndarray,
        labels: np.ndarray,
    ) -> list[dict[str, float]]:
        """Run the full training loop for ``config.epochs`` epochs.

        Checkpoints are saved to ``config.checkpoint_dir`` every
        ``config.log_interval`` epochs and at the final epoch.

        Args:
            states: Float32 array of shape ``(N, input_size)``.
            labels: Float32 array of shape ``(N,)`` with scramble depths.

        Returns:
            List of per-epoch metric dicts (same format as :meth:`train_epoch`).
        """
        self.config.checkpoint_dir.mkdir(parents=True, exist_ok=True)
        history: list[dict[str, float]] = []

        try:
            from tqdm import tqdm
            epoch_bar = tqdm(range(1, self.config.epochs + 1), desc="CNN", unit="epoch", dynamic_ncols=True)
        except ImportError:
            epoch_bar = range(1, self.config.epochs + 1)

        for epoch in epoch_bar:
            metrics = self.train_epoch(states, labels)
            history.append(metrics)

            if hasattr(epoch_bar, "set_postfix"):
                epoch_bar.set_postfix(loss=f"{metrics['loss']:.4f}", mae=f"{metrics['mae']:.4f}")

            if epoch % self.config.log_interval == 0 or epoch == self.config.epochs:
                self._logger.info(
                    "Epoch %d/%d | loss=%.4f | mae=%.4f",
                    epoch,
                    self.config.epochs,
                    metrics["loss"],
                    metrics["mae"],
                )
                ckpt_path = self.config.checkpoint_dir / f"ckpt_epoch_{epoch:04d}.npz"
                self.save_checkpoint(ckpt_path, epoch)

        return history

    def save_checkpoint(self, path: Path, epoch: int) -> None:
        """Persist model weights to a ``.npz`` file.

        The file stores all model parameters plus a scalar ``epoch`` entry so
        that training can be resumed later.

        Args:
            path:  Destination file path (will be created or overwritten).
            epoch: Current epoch number, stored inside the checkpoint.
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        params = dict(self.model.parameters())
        # Flatten nested parameter dicts so savez receives keyword args.
        flat: dict[str, mx.array] = {}
        self._flatten_params(params, "", flat)
        flat["__epoch__"] = mx.array(epoch)
        mx.savez(str(path), **flat)
        self._logger.debug("Checkpoint saved → %s", path)

    def load_checkpoint(self, path: Path) -> int:
        """Load model weights from a ``.npz`` checkpoint file.

        Args:
            path: Path to the ``.npz`` file produced by :meth:`save_checkpoint`.

        Returns:
            The epoch number that was stored in the checkpoint.
        """
        weights = mx.load(str(path))
        epoch = int(weights.pop("__epoch__"))
        # Rebuild nested structure expected by load_weights.
        self.model.load_weights(list(weights.items()))
        mx.eval(self.model.parameters())
        self._logger.debug("Checkpoint loaded ← %s (epoch %d)", path, epoch)
        return epoch

    # ------------------------------------------------------------------
    # Private utilities
    # ------------------------------------------------------------------

    @staticmethod
    def _flatten_params(
        params: dict,
        prefix: str,
        out: dict[str, mx.array],
    ) -> None:
        """Recursively flatten a nested parameter dict into ``out``.

        Keys are joined with ``'.'`` separators, which are safe for ``mx.savez``.
        Dots in ``mx.load`` keys are preserved and can be used to reconstruct
        the nested structure via :meth:`nn.Module.load_weights`.
        """
        for k, v in params.items():
            full_key = f"{prefix}.{k}" if prefix else k
            if isinstance(v, dict):
                CNNTrainer._flatten_params(v, full_key, out)
            elif isinstance(v, list):
                for idx, item in enumerate(v):
                    list_key = f"{full_key}.{idx}"
                    if isinstance(item, dict):
                        CNNTrainer._flatten_params(item, list_key, out)
                    else:
                        out[list_key] = item
            else:
                out[full_key] = v
