"""Training data generation via random walks (Autodidactic Iteration approach).

Samples are produced by applying *k* random moves from the solved state, where
*k* is drawn from a curriculum distribution.  This avoids the distribution
bias that would arise from solving puzzles and replaying the solution.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

import numpy as np

from rubiks_solve.core.base import AbstractPuzzle
from rubiks_solve.encoding.base import AbstractStateEncoder


@dataclass
class ScrambleDataset:
    """Generate ``(encoded_state, distance_label)`` pairs via random walks.

    Uses the *Autodidactic Iteration* approach: training samples are produced by
    applying *k* random moves from the **solved** state, where *k* is sampled
    from a uniform curriculum distribution ``[min_depth, max_depth]``.

    This is intentionally **not** generated by solving puzzles and replaying
    their solutions — that approach biases the sample distribution toward
    states reachable by the current solver, which slows learning on hard
    scrambles.

    Attributes:
        puzzle_factory: Zero-argument callable that returns a solved
                        :class:`~rubiks_solve.core.base.AbstractPuzzle`
                        instance.  Called once per sample.
        encoder:        Encoder used to convert puzzle state arrays into
                        model-ready tensors.
        rng:            NumPy random generator.  Pass a seeded generator for
                        reproducibility.

    Example::

        rng = np.random.default_rng(42)
        dataset = ScrambleDataset(
            puzzle_factory=Cube3x3.solved_state,
            encoder=OneHotEncoder(),
            rng=rng,
        )
        states, depths = dataset.generate_batch(batch_size=256, max_depth=20)
    """

    puzzle_factory: Callable[[], AbstractPuzzle]
    encoder: AbstractStateEncoder
    rng: np.random.Generator

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_batch(
        self,
        batch_size: int,
        min_depth: int = 1,
        max_depth: int = 20,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Generate a batch of ``(encoded_state, depth)`` pairs.

        For each sample a scramble depth *k* is drawn uniformly from
        ``[min_depth, max_depth]`` and *k* random moves are applied to a
        freshly solved puzzle.  The resulting state is encoded and paired with
        *k* as the distance label.

        Args:
            batch_size: Number of samples to generate.
            min_depth:  Minimum scramble depth (inclusive).
            max_depth:  Maximum scramble depth (inclusive).

        Returns:
            A tuple ``(encoded_states, depths)`` where

            * ``encoded_states`` has shape ``(batch_size, *encoder.output_shape)``
              and dtype ``float32``.
            * ``depths`` has shape ``(batch_size,)`` and dtype ``int64``.
        """
        if min_depth < 1:
            raise ValueError(f"min_depth must be >= 1, got {min_depth}.")
        if max_depth < min_depth:
            raise ValueError(
                f"max_depth ({max_depth}) must be >= min_depth ({min_depth})."
            )

        encoded_list: list[np.ndarray] = []
        depths: list[int] = []

        for _ in range(batch_size):
            depth = int(self.rng.integers(min_depth, max_depth + 1))
            puzzle = self.puzzle_factory().scramble(depth, self.rng)
            encoded_list.append(self.encoder.encode(puzzle))
            depths.append(depth)

        encoded_states = np.stack(encoded_list, axis=0)  # (N, *output_shape)
        depth_array = np.array(depths, dtype=np.int64)   # (N,)
        return encoded_states, depth_array

    def generate_policy_batch(
        self,
        batch_size: int,
        min_depth: int = 1,
        max_depth: int = 20,
        _n_actions: int = 18,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Generate a batch of ``(state, optimal_move_index)`` pairs for policy training.

        The *optimal move* is defined as the **inverse of the last scramble move**
        (1-step lookahead).  For a puzzle scrambled by moves ``[m_0, …, m_{k-1}]``
        the optimal action from state ``s_k`` is ``m_{k-1}.inverse()``.

        The returned move indices align with ``puzzle.legal_moves()``.  If the
        inverse move cannot be found in the legal-move list the sample is still
        included but its label is set to ``-1``.

        Args:
            batch_size: Number of samples to generate.
            min_depth:  Minimum scramble depth (inclusive).
            max_depth:  Maximum scramble depth (inclusive).
            n_actions:  Expected number of legal moves (used only to pre-validate;
                        the actual index is derived from the move list).

        Returns:
            A tuple ``(states, optimal_move_indices)`` where

            * ``states`` has shape ``(batch_size, *encoder.output_shape)`` and
              dtype ``float32``.
            * ``optimal_move_indices`` has shape ``(batch_size,)`` and dtype
              ``int64``.  Values are in ``[0, n_legal_moves)`` or ``-1`` if the
              inverse could not be located.
        """
        if min_depth < 1:
            raise ValueError(f"min_depth must be >= 1, got {min_depth}.")
        if max_depth < min_depth:
            raise ValueError(
                f"max_depth ({max_depth}) must be >= min_depth ({min_depth})."
            )

        encoded_list: list[np.ndarray] = []
        label_list: list[int] = []

        for _ in range(batch_size):
            depth = int(self.rng.integers(min_depth, max_depth + 1))
            solved_puzzle = self.puzzle_factory()
            legal_moves = solved_puzzle.legal_moves()

            # Apply depth random moves, tracking the move sequence.
            puzzle = solved_puzzle
            last_move = None
            for _step in range(depth):
                move_idx = int(self.rng.integers(0, len(legal_moves)))
                move = legal_moves[move_idx]
                puzzle = puzzle.apply_move(move)
                last_move = move

            encoded_list.append(self.encoder.encode(puzzle))

            # Optimal action = inverse of the last scramble move.
            if last_move is not None:
                target_move = last_move.inverse()
                # Find its index in the legal-move list by name.
                move_names = [m.name for m in legal_moves]
                if target_move.name in move_names:
                    label_list.append(move_names.index(target_move.name))
                else:
                    # Fallback: match by (face, layer, direction, double).
                    found = -1
                    for idx, m in enumerate(legal_moves):
                        if (
                            m.face == target_move.face
                            and m.layer == target_move.layer
                            and m.direction == target_move.direction
                            and m.double == target_move.double
                        ):
                            found = idx
                            break
                    label_list.append(found)
            else:
                # depth == 0 edge-case: already solved; no meaningful label.
                label_list.append(-1)

        states = np.stack(encoded_list, axis=0)
        labels = np.array(label_list, dtype=np.int64)
        return states, labels
